### ISSUE TITLE
Contact Form Validation for the Message 

### ISSUE THREAD

**Issue by SadeeshaJayaweera** [kulan01/beatstore#4]
I would like to request the addition of message validation using JavaScript for the contact form. Currently, we have validation for the name and email fields, but it would be helpful to also validate the message field to ensure that users provide a valid message.

Please Assign me this issue under Hactoberfest_2023.

Thanks @kulan01 & Happy Coding 🧑‍💻

**Comment by kulan01** [comment]
Thanks and Happy contributing
